name: Build KIO Assistant APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Android structure & manifest generate karo
      - name: Re-create Android Project Files
        run: flutter create . --platforms=android --org=com.ashaz.kio

      # Permissions automatically AndroidManifest me inject karo
      - name: Inject Permissions to Manifest
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />\n    <uses-permission android:name="android.permission.RECORD_AUDIO" />\n    <uses-permission android:name="android.permission.CAMERA" />' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KIO-Assistant-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
